// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PhamQuocHuy_Template.Data;

namespace PhamQuocHuy_Template.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240525145605_Updatedata2")]
    partial class Updatedata2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PhamQuocHuy_Template.Models.Industries", b =>
                {
                    b.Property<int>("IdIndustries")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NameIndust")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdIndustries");

                    b.ToTable("Industries");
                });

            modelBuilder.Entity("PhamQuocHuy_Template.Models.IndustriesDetails", b =>
                {
                    b.Property<int>("IdIndustDetails")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdIndustries")
                        .HasColumnType("int");

                    b.Property<int>("IdUser")
                        .HasColumnType("int");

                    b.HasKey("IdIndustDetails");

                    b.HasIndex("IdIndustries");

                    b.HasIndex("IdUser");

                    b.ToTable("IndustriesDetails");
                });

            modelBuilder.Entity("PhamQuocHuy_Template.Models.Users", b =>
                {
                    b.Property<int>("IdUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Birth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdUser");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PhamQuocHuy_Template.Models.IndustriesDetails", b =>
                {
                    b.HasOne("PhamQuocHuy_Template.Models.Industries", "Industries")
                        .WithMany("IndustriesDetails")
                        .HasForeignKey("IdIndustries")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PhamQuocHuy_Template.Models.Users", "Users")
                        .WithMany("IndustriesDetails")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Industries");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("PhamQuocHuy_Template.Models.Industries", b =>
                {
                    b.Navigation("IndustriesDetails");
                });

            modelBuilder.Entity("PhamQuocHuy_Template.Models.Users", b =>
                {
                    b.Navigation("IndustriesDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
